import { Inter } from "next/font/google";
import '../styles/globals.css';
import Header from "@/components/header/Header"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, params: { locale }
}) {
  console.log('-----Layout is rendred-----')
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
